/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NfcRouteImport } from './routes/nfc'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as FinRouteImport } from './routes/fin'
import { Route as EscanearRouteImport } from './routes/escanear'
import { Route as AccesibilidadRouteImport } from './routes/accesibilidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuntoIdRouteImport } from './routes/punto.$id'
import { Route as BeaconIdRouteImport } from './routes/beacon.$id'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcRoute = NfcRouteImport.update({
  id: '/nfc',
  path: '/nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const FinRoute = FinRouteImport.update({
  id: '/fin',
  path: '/fin',
  getParentRoute: () => rootRouteImport,
} as any)
const EscanearRoute = EscanearRouteImport.update({
  id: '/escanear',
  path: '/escanear',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesibilidadRoute = AccesibilidadRouteImport.update({
  id: '/accesibilidad',
  path: '/accesibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuntoIdRoute = PuntoIdRouteImport.update({
  id: '/punto/$id',
  path: '/punto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BeaconIdRoute = BeaconIdRouteImport.update({
  id: '/beacon/$id',
  path: '/beacon/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/escanear': typeof EscanearRoute
  '/fin': typeof FinRoute
  '/mapa': typeof MapaRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/beacon/$id': typeof BeaconIdRoute
  '/punto/$id': typeof PuntoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/escanear': typeof EscanearRoute
  '/fin': typeof FinRoute
  '/mapa': typeof MapaRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/beacon/$id': typeof BeaconIdRoute
  '/punto/$id': typeof PuntoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accesibilidad': typeof AccesibilidadRoute
  '/escanear': typeof EscanearRoute
  '/fin': typeof FinRoute
  '/mapa': typeof MapaRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/beacon/$id': typeof BeaconIdRoute
  '/punto/$id': typeof PuntoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesibilidad'
    | '/escanear'
    | '/fin'
    | '/mapa'
    | '/nfc'
    | '/perfil'
    | '/beacon/$id'
    | '/punto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesibilidad'
    | '/escanear'
    | '/fin'
    | '/mapa'
    | '/nfc'
    | '/perfil'
    | '/beacon/$id'
    | '/punto/$id'
  id:
    | '__root__'
    | '/'
    | '/accesibilidad'
    | '/escanear'
    | '/fin'
    | '/mapa'
    | '/nfc'
    | '/perfil'
    | '/beacon/$id'
    | '/punto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccesibilidadRoute: typeof AccesibilidadRoute
  EscanearRoute: typeof EscanearRoute
  FinRoute: typeof FinRoute
  MapaRoute: typeof MapaRoute
  NfcRoute: typeof NfcRoute
  PerfilRoute: typeof PerfilRoute
  BeaconIdRoute: typeof BeaconIdRoute
  PuntoIdRoute: typeof PuntoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc': {
      id: '/nfc'
      path: '/nfc'
      fullPath: '/nfc'
      preLoaderRoute: typeof NfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin': {
      id: '/fin'
      path: '/fin'
      fullPath: '/fin'
      preLoaderRoute: typeof FinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escanear': {
      id: '/escanear'
      path: '/escanear'
      fullPath: '/escanear'
      preLoaderRoute: typeof EscanearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesibilidad': {
      id: '/accesibilidad'
      path: '/accesibilidad'
      fullPath: '/accesibilidad'
      preLoaderRoute: typeof AccesibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punto/$id': {
      id: '/punto/$id'
      path: '/punto/$id'
      fullPath: '/punto/$id'
      preLoaderRoute: typeof PuntoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beacon/$id': {
      id: '/beacon/$id'
      path: '/beacon/$id'
      fullPath: '/beacon/$id'
      preLoaderRoute: typeof BeaconIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccesibilidadRoute: AccesibilidadRoute,
  EscanearRoute: EscanearRoute,
  FinRoute: FinRoute,
  MapaRoute: MapaRoute,
  NfcRoute: NfcRoute,
  PerfilRoute: PerfilRoute,
  BeaconIdRoute: BeaconIdRoute,
  PuntoIdRoute: PuntoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
